version: '3'

volumes:
  m2:
    driver: local
  rabbitmq:
    driver: local

services:
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    ports:
      - ${API_PORT}:8080
    environment:
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_USER: "${RABBITMQ_USER}"
      RABBITMQ_PASS: "${RABBITMQ_PASS}"
    links:
      - rabbitmq
    volumes:
      - m2:/root/.m2/

  rabbitmq:
    image: rabbitmq:3.7-management
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASS}"
    volumes:
      - rabbitmq:/var/lib/rabbitmq/
